version: "3.1"

services:
    ### Database ################################################
    database:
        container_name: boilerplate-go-mysql
        image: mysql:5.7.25
        env_file: .env
        ports:
            - 3306:${DB_PORT}
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        volumes:
#            FIXME: because migration schema has been in the infrastructure/databases.init.go
#            - ./schema/:/docker-entrypoint-initdb.d/
            - db_data:/var/lib/mysql

    ### Redis ################################################
    redis:
        image: redis
        env_file: .env
        container_name: boilerplate-go-redis
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
networks:
    apps:
        driver: bridge

volumes:
    db_data:
    redis_data: