// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	omdb "github.com/alhamsya/boilerplate-go/transport/exter/omdb"
	mock "github.com/stretchr/testify/mock"
)

// CacheRepo is an autogenerated mock type for the CacheRepo type
type CacheRepo struct {
	mock.Mock
}

// DecrKYCByStatus provides a mock function with given fields: ctx, statusKYC
func (_m *CacheRepo) DecrKYCByStatus(ctx context.Context, statusKYC int64) error {
	ret := _m.Called(ctx, statusKYC)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, statusKYC)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDetailMovie provides a mock function with given fields: ctx, movieID
func (_m *CacheRepo) GetDetailMovie(ctx context.Context, movieID string) (*omdb.OMDBDetail, error) {
	ret := _m.Called(ctx, movieID)

	var r0 *omdb.OMDBDetail
	if rf, ok := ret.Get(0).(func(context.Context, string) *omdb.OMDBDetail); ok {
		r0 = rf(ctx, movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*omdb.OMDBDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, movieID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetKYCByStatus provides a mock function with given fields: ctx, statusKYC
func (_m *CacheRepo) GetKYCByStatus(ctx context.Context, statusKYC int64) (int, error) {
	ret := _m.Called(ctx, statusKYC)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int64) int); ok {
		r0 = rf(ctx, statusKYC)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, statusKYC)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListMovie provides a mock function with given fields: ctx, search, page
func (_m *CacheRepo) GetListMovie(ctx context.Context, search string, page int64) (*omdb.OMDBList, error) {
	ret := _m.Called(ctx, search, page)

	var r0 *omdb.OMDBList
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) *omdb.OMDBList); ok {
		r0 = rf(ctx, search, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*omdb.OMDBList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, search, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrKYCByStatus provides a mock function with given fields: ctx, statusKYC
func (_m *CacheRepo) IncrKYCByStatus(ctx context.Context, statusKYC int64) error {
	ret := _m.Called(ctx, statusKYC)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, statusKYC)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetDetailMovie provides a mock function with given fields: ctx, movieID, req
func (_m *CacheRepo) SetDetailMovie(ctx context.Context, movieID string, req *omdb.OMDBDetail) error {
	ret := _m.Called(ctx, movieID, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *omdb.OMDBDetail) error); ok {
		r0 = rf(ctx, movieID, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetKYCByStatus provides a mock function with given fields: ctx, statusKYC, value
func (_m *CacheRepo) SetKYCByStatus(ctx context.Context, statusKYC int64, value int) error {
	ret := _m.Called(ctx, statusKYC, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int) error); ok {
		r0 = rf(ctx, statusKYC, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetListMovie provides a mock function with given fields: ctx, search, page, req
func (_m *CacheRepo) SetListMovie(ctx context.Context, search string, page int64, req *omdb.OMDBList) error {
	ret := _m.Called(ctx, search, page, req)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, *omdb.OMDBList) error); ok {
		r0 = rf(ctx, search, page, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
