// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	wrapper "github.com/alhamsya/boilerplate-go/infrastructure/wrapper"
)

// CallWrapperRepo is an autogenerated mock type for the CallWrapperRepo type
type CallWrapperRepo struct {
	mock.Mock
}

// GetWrapper provides a mock function with given fields: usecase
func (_m *CallWrapperRepo) GetWrapper(usecase string) *wrapper.Wrapper {
	ret := _m.Called(usecase)

	var r0 *wrapper.Wrapper
	if rf, ok := ret.Get(0).(func(string) *wrapper.Wrapper); ok {
		r0 = rf(usecase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*wrapper.Wrapper)
		}
	}

	return r0
}
