// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	omdb "github.com/alhamsya/boilerplate-go/infrastructure/external/omdb"
	mock "github.com/stretchr/testify/mock"
)

// OMDBRepo is an autogenerated mock type for the OMDBRepo type
type OMDBRepo struct {
	mock.Mock
}

// GetDetailMovie provides a mock function with given fields: movieID
func (_m *OMDBRepo) GetDetailMovie(movieID string) (*omdb.OMDBDetail, error) {
	ret := _m.Called(movieID)

	var r0 *omdb.OMDBDetail
	if rf, ok := ret.Get(0).(func(string) *omdb.OMDBDetail); ok {
		r0 = rf(movieID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*omdb.OMDBDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(movieID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListMovie provides a mock function with given fields: search, page
func (_m *OMDBRepo) GetListMovie(search string, page int64) (*omdb.OMDBList, error) {
	ret := _m.Called(search, page)

	var r0 *omdb.OMDBList
	if rf, ok := ret.Get(0).(func(string, int64) *omdb.OMDBList); ok {
		r0 = rf(search, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*omdb.OMDBList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int64) error); ok {
		r1 = rf(search, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
