// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	modelMovie "github.com/alhamsya/boilerplate-go/domain/models/movie"
	mock "github.com/stretchr/testify/mock"
)

// ServiceRepo is an autogenerated mock type for the ServiceRepo type
type ServiceRepo struct {
	mock.Mock
}

// CreateHistoryLog provides a mock function with given fields: ctx, reqDB
func (_m *ServiceRepo) CreateHistoryLog(ctx context.Context, reqDB *modelMovie.DBHistoryLog) (int64, error) {
	ret := _m.Called(ctx, reqDB)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *modelMovie.DBHistoryLog) int64); ok {
		r0 = rf(ctx, reqDB)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *modelMovie.DBHistoryLog) error); ok {
		r1 = rf(ctx, reqDB)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
