// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SpotifyRepo is an autogenerated mock type for the SpotifyRepo type
type SpotifyRepo struct {
	mock.Mock
}

// GetTopTracks provides a mock function with given fields: limit
func (_m *SpotifyRepo) GetTopTracks(limit int) error {
	ret := _m.Called(limit)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(limit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
