// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	spotify "github.com/alhamsya/boilerplate-go/infrastructure/external/spotify"
)

// SpotifyRepo is an autogenerated mock type for the SpotifyRepo type
type SpotifyRepo struct {
	mock.Mock
}

// GetUser provides a mock function with given fields:
func (_m *SpotifyRepo) GetUser() (*spotify.Profile, error) {
	ret := _m.Called()

	var r0 *spotify.Profile
	if rf, ok := ret.Get(0).(func() *spotify.Profile); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*spotify.Profile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
