// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UtilsRepo is an autogenerated mock type for the UtilsRepo type
type UtilsRepo struct {
	mock.Mock
}

// CurrentTimeF provides a mock function with given fields: format
func (_m *UtilsRepo) CurrentTimeF(format string) (string, error) {
	ret := _m.Called(format)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(format)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(format)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
