// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// HelpersRepo is an autogenerated mock type for the HelpersRepo type
type HelpersRepo struct {
	mock.Mock
}

// Tes provides a mock function with given fields: ctx
func (_m *HelpersRepo) Tes(ctx context.Context) bool {
	ret := _m.Called(ctx)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
